-- FarmFinder CNY first-party analytics events
-- Run this migration in Supabase to enable privacy-conscious event tracking.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text,
  farm_id uuid,
  product_query text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_event_name_idx on public.analytics_events(event_name);
create index if not exists analytics_events_farm_id_idx on public.analytics_events(farm_id);

alter table public.analytics_events enable row level security;

-- Visitors may record analytics, but cannot read the analytics table.
drop policy if exists "public can insert analytics events" on public.analytics_events;
create policy "public can insert analytics events"
on public.analytics_events for insert
to anon, authenticated
with check (
  event_name in (
    'page_view',
    'product_search',
    'farm_detail_view',
    'directions_click',
    'add_farm_start',
    'add_farm_submit',
    'farmer_inventory_update'
  )
);

-- Useful admin rollup. Access this from trusted/admin server code, not the public client.
create or replace view public.analytics_daily_summary as
select
  date_trunc('day', created_at) as day,
  count(*) filter (where event_name = 'page_view') as page_views,
  count(distinct session_id) filter (where event_name = 'page_view') as visitor_sessions,
  count(*) filter (where event_name = 'product_search') as product_searches,
  count(*) filter (where event_name = 'farm_detail_view') as farm_detail_views,
  count(*) filter (where event_name = 'directions_click') as directions_clicks,
  count(*) filter (where event_name = 'add_farm_start') as add_farm_starts,
  count(*) filter (where event_name = 'add_farm_submit') as add_farm_submissions,
  count(*) filter (where event_name = 'farmer_inventory_update') as farmer_inventory_updates
from public.analytics_events
group by 1
order by 1 desc;
