import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

type HealthCheck = { key: string; label: string; status: "healthy" | "warning" | "error"; detail: string };
const normalize = (value: string | null | undefined) => (value ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
export async function GET(request: Request) {
  const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL,publishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY,authorization=request.headers.get("authorization");
  if(!supabaseUrl||!publishableKey||!serviceRoleKey)return NextResponse.json({error:"System health is not configured."},{status:503});
  if(!authorization?.startsWith("Bearer "))return NextResponse.json({error:"Authentication required."},{status:401});
  const userClient=createClient(supabaseUrl,publishableKey,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:authorization}}});
  const {data:userData}=await userClient.auth.getUser(authorization.slice("Bearer ".length)); if(!userData.user)return NextResponse.json({error:"Authentication required."},{status:401});
  const serviceClient=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}}); const {data:admin}=await serviceClient.from("admin_users").select("user_id").eq("user_id",userData.user.id).maybeSingle(); if(!admin)return NextResponse.json({error:"Administrator access required."},{status:403});
  const [farms,inventory,subscriptions,submissions,claims,updates,submissionFarms,submissionPending,approvedOwners]=await Promise.all([
    serviceClient.from("farm_stands").select("id,name,address,city,state,zip_code,latitude,longitude,owner_user_id,owner_access_activated_at,farmer_inventory_updated_at,is_active"),
    serviceClient.from("farm_inventory").select("id,farm_id,status,updated_at").limit(1),serviceClient.from("inventory_alert_subscriptions").select("id,farm_id,active").limit(1),serviceClient.from("farm_stand_submissions").select("id,status,submission_type").limit(1),serviceClient.from("farm_claim_requests").select("id,status,requested_by,farm_id").limit(1),serviceClient.from("farm_update_requests").select("id,status,requested_by,farm_id").limit(1),serviceClient.from("farm_stands").select("id,name,address,city,state,zip_code").eq("is_active",true).limit(1),serviceClient.from("farm_stand_submissions").select("id,submission_type,farm_name,address,city,state,zip_code").eq("status","pending").limit(1),serviceClient.from("farm_stand_submissions").select("id,farm_name,address,city,state,zip_code,contact_email").eq("submission_type","owner").eq("status","approved")
  ]);
  const checks:HealthCheck[]=[]; const databaseResults=[farms,inventory,subscriptions,submissions,claims,updates],databaseError=databaseResults.find(r=>r.error)?.error;
  checks.push(databaseError?{key:"database",label:"Core database structure",status:"error",detail:databaseError.message}:{key:"database",label:"Core database structure",status:"healthy",detail:"Required owner, inventory, alert, submission, claim, and update fields are available."});
  const submissionPathError=submissionFarms.error??submissionPending.error; checks.push(submissionPathError?{key:"public-submissions",label:"Farm submission API",status:"error",detail:`The server submission path cannot perform its required checks: ${submissionPathError.message}`}:{key:"public-submissions",label:"Farm submission API",status:"healthy",detail:"The server can securely check active listings and pending submissions before accepting a farm submission."});
  const activeFarms=(farms.data??[]).filter(f=>f.is_active);
  if(approvedOwners.error||farms.error){checks.push({key:"owner-activation",label:"Owner activation chain",status:"error",detail:approvedOwners.error?.message??farms.error?.message??"Owner records could not be checked."});}
  else {const orphaned=(approvedOwners.data??[]).filter(s=>!activeFarms.some(f=>normalize(f.name)===normalize(s.farm_name)&&normalize(f.address)===normalize(s.address)&&normalize(f.city)===normalize(s.city)&&normalize(f.state)===normalize(s.state)&&normalize(f.zip_code)===normalize(s.zip_code))); checks.push(orphaned.length?{key:"owner-activation",label:"Owner activation chain",status:"warning",detail:`${orphaned.length} approved owner submission${orphaned.length===1?" does":"s do"} not safely match an active farm. Review Owner Access Check before resending invitations.`}:{key:"owner-activation",label:"Owner activation chain",status:"healthy",detail:`All ${(approvedOwners.data??[]).length} approved owner submission${(approvedOwners.data??[]).length===1?"":"s"} safely match an active farm for automatic portal connection.`});}
  checks.push(process.env.RESEND_API_KEY?{key:"email",label:"Email delivery configuration",status:"healthy",detail:"The server email connection is configured."}:{key:"email",label:"Email delivery configuration",status:"error",detail:"RESEND_API_KEY is missing."});
  const missingCoordinates=activeFarms.filter(f=>f.latitude===null||f.longitude===null||!Number.isFinite(Number(f.latitude))||!Number.isFinite(Number(f.longitude))); checks.push(missingCoordinates.length?{key:"coordinates",label:"Active farm map locations",status:"warning",detail:`${missingCoordinates.length} active farm${missingCoordinates.length===1?" is":"s are"} missing valid coordinates.`}:{key:"coordinates",label:"Active farm map locations",status:"healthy",detail:"Every active farm has valid map coordinates."});
  const groups=new Map<string,number>(); for(const farm of activeFarms){const key=[normalize(farm.name),normalize(farm.address),normalize(farm.city)].join("|");if(key!=="||")groups.set(key,(groups.get(key)??0)+1);} const duplicateGroups=Array.from(groups.values()).filter(c=>c>1).length; checks.push(duplicateGroups?{key:"duplicates",label:"Duplicate active listings",status:"warning",detail:`${duplicateGroups} possible duplicate group${duplicateGroups===1?"":"s"} found by name and address.`}:{key:"duplicates",label:"Duplicate active listings",status:"healthy",detail:"No duplicate active farms were found by name and address."});
  const overall=checks.some(c=>c.status==="error")?"error":checks.some(c=>c.status==="warning")?"warning":"healthy"; return NextResponse.json({overall,checked_at:new Date().toISOString(),checks});
}
